apiVersion: v1                                                                                                
kind: Service                                                                                                 
metadata:                                                                                                     
  name: nginx-phpfpm                                                                                        
spec:                                                                                                         
   type: NodePort                                                                                             
   selector:                                                                                                  
     app: nginx-phpfpm                                                                                        
   ports:                                                                                                     
     - port: 8092                                                                                               
       targetPort: 8092                           
       nodePort: 30012