apiVersion: v1
kind: Pod
metadata:
  name: secret-datacenter
spec:
  containers:
  - name: secret-container-datacenter
    image: ubuntu:latest
    command: ["/bin/sh", "-c", "sleep 3600"]
    volumeMounts:
    - name: blog-secret
      mountPath: /opt/demo
  volumes:
  - name: blog-secret
    secret:
      secretName: blog
