apiVersion: v1
kind: Service
metadata:
  name: tomcat-service-devops
  namespace: tomcat-namespace-devops
spec:
  selector:
    app: tomcat-app
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 32227
